version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket <BUCKET_NAME> --output-template-file packaged-template.yaml
artifacts:
  files:
    - template.yaml
    - packaged-template.yaml