AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'aqi-app SAM Template for aqi-app

  '
Globals:
  Function:
    Timeout: 180
    Runtime: python3.8
    Environment:
      Variables:
        RAW_TABLE_NAME: SensorsDataTable
        TRANSFORMED_TABLE_NAME: TransformedDataTable
        TZ: Asia/Calcutta
Resources:
  SensorsDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Date-Time
        Type: String
      TableName: SensorsDataTable
      Tags:
        Project: aqi-app
  TransformedDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Date-Time
        Type: String
      TableName: TransformedDataTable
      Tags:
        Project: aqi-app
  ScrapperFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Scrapper
      CodeUri: s3://aqi-app-bucket/452855922289c541b185d3e11dfe6571
      Handler: app.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: rate(60 minutes)
  TransformFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Transform
      CodeUri: s3://aqi-app-bucket/01f87df86ff657b98e3465e59699183e
      Handler: app.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: rate(70 minutes)
