AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aqi-app
  SAM Template for aqi-app

Globals:
  Function:    
    Timeout: 420  
    MemorySize: 2000      
    Environment:
      Variables:
        RAW_TABLE_NAME: SensorsDataTable
        TRANSFORMED_TABLE_NAME: TransformedDataTable
        FORECAST_TABLE_NAME: ForecastTable
        TZ: Asia/Calcutta

Resources:  
# DynamoDB Tables _______________________________
  SensorsDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Date-Time
        Type: String        
      TableName: SensorsDataTable
      Tags: 
        Project: aqi-app

  TransformedDataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Date-Time
        Type: String        
      TableName: TransformedDataTable
      Tags: 
        Project: aqi-app

  ForecastTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Date-Time
        Type: String        
      TableName: ForecastTable
      Tags: 
        Project: aqi-app

# Lambda Functions _______________________________
  ScrapperFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Runtime: python3.8
      FunctionName: Scrapper
      CodeUri: Scrapper/      
      Handler: app.lambda_handler           
      Policies: AmazonDynamoDBFullAccess 
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: 'rate(60 minutes)'
  
  TransformFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Runtime: python3.8
      FunctionName: Transform
      CodeUri: Transform/      
      Handler: app.lambda_handler           
      Policies: AmazonDynamoDBFullAccess 
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: 'rate(30 minutes)'
  
  ForecastFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: Forecast
      PackageType: Image
      Policies:        
        - AWSLambdaExecute 
        - AmazonDynamoDBFullAccess 
      Events:           
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: 'rate(30 minutes)'   
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./Forecast
      DockerTag: forecast