AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aqi-app
  SAM Template for aqi-app
  
Globals:
  Function:
    Runtime: python3.8
    Timeout: 180
    Policies: AmazonDynamoDBFullAccess
    Environment:
      Variables:
        TABLE_NAME: SensorsDataTable

Resources:  
  SensorsDataTable:
  Type: AWS::Serverless::SimpleTable
  Properties:
    PrimaryKey:
      Name: Date-Time
      Type: String   
    TableName: SensorsDataTable
    Tags: 
      Project: aqi-app

  

  ScrapperFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: Scrapper/
      Handler: app.lambda_handler      
      Events:
        Scheduler:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
