AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aqi-app

  Sample SAM Template for aqi-app


Globals:
  Function:
    Timeout: 3

Resources:
  ScrapperFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: Scrapper/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

